let q="#################################################";
let x="              ESS ESS CONVENT SCHOOL            ";
let y="NAME = mohinish gautam";
let z="GRADE = VII";
let a="                       SECTION = D";
let b="roll no = 123456789";
let c="-------------------------------------------------";
let d="PHYSICS";
let e="                                  65/70";
let f="CHEMISTRY";
let g="                                63/70";
let h="MATHS";
let i="                                    67/70";
let w="#################################################";
console.log(q);
console.log(x);
console.log(y);
console.log(z,a);
console.log(b);
console.log(c);
console.log(d,e);
console.log(f,g);
console.log(h,i);
console.log(w);
